create database text_number_converter;


create table text_number_converter.public.convert_log
(
    id          bigint generated by default as identity
        primary key,
    inner_value varchar(255),
    outer_value varchar(255),
    type        varchar(255),
    user_name   varchar(255)
);

alter table text_number_converter.public.convert_log
    owner to postgres;

